export * from './aboutPage';
export * from './mainPage';
export * from './not-found-page';
export * from './profilePage';
export * from './articlesPage';
export * from './articleDetailsPage';
export * from './articleEditPage';
export * from './adminPage';
export * from './forbiddenPage';
